# Generated by Django 3.2.16 on 2023-03-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_notification_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['recieved_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
    ]
