# Generated by Django 3.2.16 on 2023-03-31 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20230331_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dwhenjhig/image/upload/v1680266745/media/images/posted_pics/default_xfmhpy.jpg', max_length=255, verbose_name='image'),
        ),
    ]
