# Generated by Django 3.2.16 on 2023-04-03 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
